version: '3.9'

services:
  kong:
    image: kong:3.0.1
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://localhost:8002
      - KONG_LICENSE_DATA
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8002:8002
      - 8445:8445
      - 8003:8003
      - 8004:8004
    volumes: 
     - /home/hm/kong_project/hello_world/declarative:/kong/declarative/
    networks:
      - kong-net
  go_app:
    build:
      context: .
      dockerfile: ./go_app/Dockerfile
    depends_on:
      - kong
    networks:
      - kong-net
networks:
  kong-net:
    external: false